In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.multioutput import MultiOutputClassifier
# example of making a single class prediction
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

In [2]:
#ast data
ad = pd.read_csv('new_repo_python_relate.csv')

## Functional and Dynamic

In [3]:
trainxor = ad[['FuncCount']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

### Bayesian

In [4]:
from sklearn import linear_model

reg = linear_model.BayesianRidge()
dn, fc = 0, 3
model = reg.fit(X_train, y_train.values.ravel())
# xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
y_pred = model.predict(xnew)
print(y_pred)

[0.61849025 0.61863427 0.61993044 0.62137063 0.62569121 0.63001178
 0.63289216]


### Gaussian 

In [5]:
gnb = GaussianNB()
dn, fc = 0, 3
model = gnb.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.44      0.98      0.61      1061
           1       0.97      0.32      0.48      1958

    accuracy                           0.55      3019
   macro avg       0.71      0.65      0.54      3019
weighted avg       0.79      0.55      0.52      3019

[[1044   17]
 [1334  624]]
Precision score: 0.9734789391575663
X=[0], Predicted=[0.952, 0.048]
X=[1], Predicted=[0.0, 1.0]
X=[10], Predicted=[0.953, 0.047]
X=[20], Predicted=[0.011, 0.989]
X=[50], Predicted=[0.952, 0.048]
X=[80], Predicted=[0.951, 0.049]
X=[100], Predicted=[0.951, 0.049]


### Logistic Regression

In [6]:
logreg = LogisticRegression()
dn, fc = 0, 3
print(y_train)
model = logreg.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))
    
    
trainxor = ad[['FuncCount']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

       Relatedness
7731             1
16835            1
1624             0
12217            1
6926             1
...            ...
13123            1
19648            0
9845             1
10799            1
2732             0

[27163 rows x 1 columns]
              precision    recall  f1-score   support

           0       0.62      0.77      0.69      1061
           1       0.86      0.75      0.80      1958

    accuracy                           0.76      3019
   macro avg       0.74      0.76      0.74      3019
weighted avg       0.78      0.76      0.76      3019

[[ 822  239]
 [ 498 1460]]
Precision score: 0.859329017068864
X=[0], Predicted=[0.574, 0.426]
X=[1], Predicted=[0.003, 0.997]
X=[10], Predicted=[0.453, 0.547]
X=[20], Predicted=[0.01, 0.99]
X=[50], Predicted=[0.574, 0.426]
X=[80], Predicted=[0.589, 0.411]
X=[100], Predicted=[0.589, 0.411]


### Neural Network

In [7]:
mlpc=MLPClassifier(hidden_layer_sizes=(12,12,12),max_iter=500)
model = mlpc.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.65      0.65      0.65      1061
           1       0.81      0.81      0.81      1958

    accuracy                           0.76      3019
   macro avg       0.73      0.73      0.73      3019
weighted avg       0.75      0.76      0.76      3019

[[ 688  373]
 [ 366 1592]]
Precision score: 0.8101781170483461
X=[0], Predicted=[0.708, 0.292]
X=[1], Predicted=[0.028, 0.972]
X=[10], Predicted=[0.317, 0.683]
X=[20], Predicted=[0.033, 0.967]
X=[50], Predicted=[0.708, 0.292]
X=[80], Predicted=[0.844, 0.156]
X=[100], Predicted=[0.844, 0.156]
