In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.multioutput import MultiOutputClassifier
# example of making a single class prediction
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

In [2]:
#ast data
ad = pd.read_csv('repo_python_relate.csv')

## Functional and Dynamic

In [3]:
trainxor = ad[['Func']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

### Bayesian

In [4]:
from sklearn import linear_model

reg = linear_model.BayesianRidge()
dn, fc = 0, 3
model = reg.fit(X_train, y_train.values.ravel())
# xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
y_pred = model.predict(xnew)
print(y_pred)

[0.45304413 0.45307188 0.45332157 0.45359902 0.45443134 0.45526366
 0.45581854]


### Gaussian 

In [5]:
gnb = GaussianNB()
dn, fc = 0, 3
model = gnb.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.58      1.00      0.74      2814
           1       0.98      0.13      0.23      2318

    accuracy                           0.61      5132
   macro avg       0.78      0.56      0.48      5132
weighted avg       0.76      0.61      0.51      5132

[[2807    7]
 [2011  307]]
Precision score: 0.9777070063694268
X=[0], Predicted=[0.981, 0.019]
X=[1], Predicted=[0.981, 0.019]
X=[10], Predicted=[0.0, 1.0]
X=[20], Predicted=[0.974, 0.026]
X=[50], Predicted=[0.981, 0.019]
X=[80], Predicted=[0.98, 0.02]
X=[100], Predicted=[0.981, 0.019]


### Logistic Regression

In [6]:
logreg = LogisticRegression()
dn, fc = 0, 3
print(y_train)
model = logreg.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))
    
    
trainxor = ad[['Func']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

       Relatedness
38194            1
34050            1
34452            0
39645            1
46518            1
...            ...
21243            1
45891            0
42613            1
43567            0
2732             0

[46187 rows x 1 columns]
              precision    recall  f1-score   support

           0       0.66      0.95      0.78      2814
           1       0.87      0.42      0.56      2318

    accuracy                           0.71      5132
   macro avg       0.77      0.68      0.67      5132
weighted avg       0.76      0.71      0.68      5132

[[2672  142]
 [1354  964]]
Precision score: 0.8716094032549728
X=[0], Predicted=[0.674, 0.326]
X=[1], Predicted=[0.664, 0.336]
X=[10], Predicted=[0.0, 1.0]
X=[20], Predicted=[0.273, 0.727]
X=[50], Predicted=[0.504, 0.496]
X=[80], Predicted=[0.492, 0.508]
X=[100], Predicted=[0.653, 0.347]


### Neural Network

In [7]:
mlpc=MLPClassifier(hidden_layer_sizes=(12,12,12),max_iter=500)
model = mlpc.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.72      0.81      0.77      2814
           1       0.73      0.62      0.67      2318

    accuracy                           0.73      5132
   macro avg       0.73      0.72      0.72      5132
weighted avg       0.73      0.73      0.72      5132

[[2293  521]
 [ 884 1434]]
Precision score: 0.7335038363171356
X=[0], Predicted=[0.889, 0.111]
X=[1], Predicted=[0.744, 0.256]
X=[10], Predicted=[0.01, 0.99]
X=[20], Predicted=[0.172, 0.828]
X=[50], Predicted=[0.304, 0.696]
X=[80], Predicted=[0.285, 0.715]
X=[100], Predicted=[0.656, 0.344]
