In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import precision_score
from sklearn.multioutput import MultiOutputClassifier
# example of making a single class prediction
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier

In [2]:
#ast data
ad = pd.read_csv('repo_python_relate.csv')

## Functional and Dynamic

In [3]:
trainxor = ad[['Func']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

### Bayesian

In [4]:
from sklearn import linear_model

reg = linear_model.BayesianRidge()
dn, fc = 0, 3
model = reg.fit(X_train, y_train.values.ravel())
# xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
y_pred = model.predict(xnew)
print(y_pred)

[0.62669966 0.62681658 0.62786891 0.62903816 0.63254592 0.63605369
 0.63839219]


### Gaussian 

In [5]:
gnb = GaussianNB()
dn, fc = 0, 3
model = gnb.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.50      0.97      0.66       112
           1       0.94      0.32      0.48       159

    accuracy                           0.59       271
   macro avg       0.72      0.65      0.57       271
weighted avg       0.76      0.59      0.55       271

[[109   3]
 [108  51]]
Precision score: 0.9444444444444444
X=[0], Predicted=[0.001, 0.999]
X=[1], Predicted=[0.939, 0.061]
X=[10], Predicted=[0.941, 0.059]
X=[20], Predicted=[0.939, 0.061]
X=[50], Predicted=[0.939, 0.061]
X=[80], Predicted=[0.941, 0.059]
X=[100], Predicted=[0.941, 0.059]


### Logistic Regression

In [6]:
logreg = LogisticRegression()
dn, fc = 0, 3
print(y_train)
model = logreg.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))
    
    
trainxor = ad[['Func']]
trainyor = ad[['Relatedness']]
X_train, X_test, y_train, y_test = train_test_split(
    trainxor, trainyor, test_size=0.1, random_state=0)

      Relatedness
1767            0
971             1
927             1
2269            0
1096            0
...           ...
1731            0
763             0
835             1
1653            1
2607            1

[2433 rows x 1 columns]
              precision    recall  f1-score   support

           0       0.64      0.74      0.69       112
           1       0.79      0.70      0.75       159

    accuracy                           0.72       271
   macro avg       0.72      0.72      0.72       271
weighted avg       0.73      0.72      0.72       271

[[ 83  29]
 [ 47 112]]
Precision score: 0.7943262411347518
X=[0], Predicted=[0.011, 0.989]
X=[1], Predicted=[0.556, 0.444]
X=[10], Predicted=[0.476, 0.524]
X=[20], Predicted=[0.556, 0.444]
X=[50], Predicted=[0.549, 0.451]
X=[80], Predicted=[0.52, 0.48]
X=[100], Predicted=[0.469, 0.531]


### Neural Network

In [13]:
mlpc=MLPClassifier(hidden_layer_sizes=(12,12,12),max_iter=500)
model = mlpc.fit(X_train, y_train.values.ravel())
y_pred = model.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test, y_pred))
print("Precision score: {}".format(precision_score(y_test,y_pred)))
xnew = [[0,1],[1,0],[0,10],[0,20],[0,50],[0,80],[0,100]]
xnew = [[0],[1],[10],[20],[50],[80],[100]]
xprobs = model.predict_proba(X_test)
for i in range(len(xnew)):
	print("X=%s, Predicted=%s" % (xnew[i], [round(xprobs[i][0],3),round(xprobs[i][1],3)]))

              precision    recall  f1-score   support

           0       0.65      0.63      0.64       112
           1       0.75      0.76      0.75       159

    accuracy                           0.71       271
   macro avg       0.70      0.70      0.70       271
weighted avg       0.71      0.71      0.71       271

[[ 71  41]
 [ 38 121]]
Precision score: 0.7469135802469136
X=[0], Predicted=[0.059, 0.941]
X=[1], Predicted=[0.605, 0.395]
X=[10], Predicted=[0.381, 0.619]
X=[20], Predicted=[0.605, 0.395]
X=[50], Predicted=[0.624, 0.376]
X=[80], Predicted=[0.479, 0.521]
X=[100], Predicted=[0.372, 0.628]
